name: topo
version: 1.0.1
description: TopoJSON is an extension of GeoJSON that encodes topology and eliminates redundancy.
repository: https://github.com/luizbarboza/topo

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  topo_client: ^1.0.3
  topo_server: ^1.0.2
  topo_simplify: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
